[server]
headless = true
enableXsrfProtection = true
port = 8501

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#55A868"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1f2e"
textColor = "#fafafa"
font = "sans serif"
